const states = {
  CHOOSEUSER: "CHOOSEUSER",
  EXISTINGUSER: "EXISTINGUSER",
  CREATEUSER: "CREATEUSER",
  PICKCLASS: "PICKCLASS",
  SINGLECLASS: "SINGLECLASS",
  PACKAGECLASS: "PACKAGECLASS",
  CONFIRM: "CONFIRM",
  PAYMENT: "PAYMENT",
  RECIPT: "RECIPT",
};

export default states;
