backend:
  name: git-gateway
  branch: netlify-CMS
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "class"
    label: "Class"
    folder: "src/pages/shedule"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start Date", name: "start", widget: "datetime" }
      - { label: "End Date", name: "end", widget: "datetime" }
      - { label: "Class Size", name: "size", widget: "string" }
